### ISSUE TITLE
Orleans Messaging Delivery Guarantees 

### ISSUE THREAD

**Issue by gabikliot** [cmeiklejohn/cmeiklejohn.github.io#14]
Hi

Thanks for putting this http://christophermeiklejohn.com/orleans.html up.
I would lime to ask you to correct one inaccuracy in your description. **Orleans Messaging Delivery Guarantees is at most once, not at least once**, as was written (by mistake) in our paper. Here is a more detailed explanation: http://dotnet.github.io/orleans/Runtime-Implementation-Details/Messaging-Delivery-Guarantees.html
Sorry for creating this confusion in the paper in the first place.

**Comment by cmeiklejohn** [comment]
Addressed by https://github.com/cmeiklejohn/cmeiklejohn.github.io/commit/1cacaae8215d19e44b0f3dcdb66e53ac45537bea.

**Comment by cmeiklejohn** [comment]
Oops, I meant https://github.com/cmeiklejohn/cmeiklejohn.github.io/commit/fe79fbb35d7dbee8a191ad59a8c8b9221c4fb5c2.

**Comment by gabikliot** [comment]
Sorry, but this is still wrong: "Orleans provides at-most-once message delivery, by resending messages that were not acknowledged after a configurable timeout".
This is dichotomy. At most once means you do **not** resend.

The correct sentence would be:
"By default Orleans provides at-most-once message delivery. In addition, only if configured to do resends, Orleans will resend messages that were not acknowledged after a configurable timeout, thus providing at least once message delivery".

**Comment by cmeiklejohn** [comment]
My apologies.  I conflated the paper description with the guarantees, assuming that you retried using a unique identifier to enforce the at-most-once guarantee.  I read the Microsoft page and now understand that a message may not be delivered unless configured to retry under a given timeout.

So, to make sure I understand correctly, if you use timeouts a message will be delivered under the at-least-once guarantee, given some messages might be delivered, acknowledgement dropped/delayed, and retransmitted?

**Comment by cmeiklejohn** [comment]
I made the following changes here https://github.com/cmeiklejohn/cmeiklejohn.github.io/commit/45dd8f8b1ce993ca368a3930b9cc3aec4c4bbebf.  Let me know if you think this is correct.

**Comment by gabikliot** [comment]
Hi. The wording in http://christophermeiklejohn.com/papers/2015/05/03/orleans.html is correct now.

>, if you use timeouts a message will be delivered under the at-least-once guarantee, given some messages might be delivered, acknowledgement dropped/delayed, and retransmitted?

All messages have timeout. Always. All messages are delivered by default under **at most once**.

**Comment by cmeiklejohn** [comment]
OK; thank you.
